version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - "8080:80"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
      - "${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: "${PROJECT_NAME}_mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    image: php:7.4-fpm
    container_name: "${PROJECT_NAME}_php"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - laravel

  artisan:
    image: php:7.4-fpm
    container_name: "${PROJECT_NAME}_artisan"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      
  composer:
    image: composer:latest
    container_name: "${PROJECT_NAME}_composer"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - "${PROJECT_DIR}:/var/www/html"
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: "${PROJECT_NAME}_npm"
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ${PROJECT_DIR}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
